<a href="https://colab.research.google.com/github/FelixManukyan7/UEFA-Top-5-Leagues/blob/main/cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
matches = pd.read_csv("all_matches.csv")
matches.columns

Index(['Unnamed: 0', 'date', 'time', 'comp', 'round', 'day', 'venue', 'result',
       'gf', 'ga', 'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain',
       'formation', 'referee', 'match report', 'notes', 'sh_x', 'sot', 'dist',
       'sot%', 'g/sh', 'g/sot', 'npxg', 'npxg/sh', 'g-xg', 'np:g-xg', 'cmp',
       'cmp.1', 'cmp.2', 'cmp.3', 'att', 'att.1', 'att.2', 'att.3', 'cmp%',
       'cmp%.1', 'cmp%.2', 'cmp%.3', 'totdist', 'prgdist', 'ast', 'xag', 'xa',
       'kp', 'tkl', 'tkl.1', 'tklw', 'def 3rd_x', 'mid 3rd_x', 'att 3rd_x',
       'blocks', 'sh_y', 'pass', 'int', 'tkl+int', 'clr', 'err', 'touches',
       'def pen', 'def 3rd_y', 'mid 3rd_y', 'att 3rd_y', 'att pen', 'live',
       'season', 'team'],
      dtype='object')

In [4]:
matches.drop(columns=['Unnamed: 0','time', 'comp', 'day', 'attendance', 'captain', 'formation', 'referee', 'match report', 'notes', 'dist'],inplace=True)
matches.drop(columns=['cmp.1', 'cmp.2', 'cmp.3', 'att.1', 'att.2', 'att.3', 'cmp%.1', 'cmp%.2', 'cmp%.3','tkl.1', 'live'],inplace=True)
matches.rename(columns={'cmp': 'completed passes', 'att': 'passes attempted' , 'cmp%': 'completed passes %'}, inplace=True)
matches.rename(columns={'def 3rd_x': 'takles def 3rd', 'mid 3rd_x': 'takles mid 3rd', 'att 3rd_x': 'takles att 3rd', 'sh_y':'shots blocked', 'pass':'passes blocked'}, inplace=True)
matches.rename(columns={'def pen': 'touches def pen', 'def 3rd_y': 'touches def 3rd', 'mid 3rd_y': 'touches mid 3rd', 'att 3rd_y': 'touches att 3rd', 'att pen': 'touches att pen'}, inplace=True)

In [5]:
matches

,date,round,venue,result,gf,ga,opponent,xg,xga,poss,...,clr,err,touches,touches def pen,touches def 3rd,touches mid 3rd,touches att 3rd,touches att pen,season,team
0,2023-08-11,Matchweek 1,Away,W,3,0,Burnley,1.9,0.3,65.0,...,7,2,835,75,267,412,158,23,2023-2024,Manchester City
1,2023-08-19,Matchweek 2,Home,W,1,0,Newcastle Utd,1.0,0.3,59.0,...,10,1,788,65,212,411,174,21,2023-2024,Manchester City
2,2023-08-27,Matchweek 3,Away,W,2,1,Sheffield Utd,3.5,0.7,79.0,...,6,0,893,40,153,440,304,53,2023-2024,Manchester City
3,2023-09-02,Matchweek 4,Home,W,5,1,Fulham,2.2,1.4,68.0,...,11,0,838,64,222,483,138,20,2023-2024,Manchester City
4,2023-09-16,Matchweek 5,Away,W,3,1,West Ham,3.6,0.9,68.0,...,9,0,837,49,148,382,311,49,2023-2024,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,2022-04-30,Matchweek 35,Away,L,0,2,Aston Villa,0.5,1.8,55.0,...,9,0,636,75,257,266,120,17,2021-2022,Norwich City
2276,2022-05-08,Matchweek 36,Home,L,0,4,West Ham,0.8,3.0,37.0,...,20,1,498,58,172,214,119,16,2021-2022,Norwich City
2277,2022-05-11,Matchweek 21,Away,L,0,3,Leicester City,1.1,2.0,35.0,...,37,0,527,96,257,184,94,18,2021-2022,Norwich City
2278,2022-05-15,Matchweek 37,Away,D,1,1,Wolves,1.1,0.9,36.0,...,23,0,470,95,248,176,57,13,2021-2022,Norwich City
2279,2022-05-22,Matchweek 38,Home,L,0,5,Tottenham,0.5,3.4,41.0,...,7,1,513,60,184,233,98,16,2021-2022,Norwich City

In [6]:
matches["date"] = pd.to_datetime(matches['date'])

In [7]:
matches["round"] = matches["round"].str.replace("Matchweek", "").astype(int)

In [8]:
matches["result"] = matches["result"].astype('category').cat.rename_categories({'W': 1, 'L': -1, 'D': 0})

In [9]:
matches["venue"] = matches["venue"].astype("category").cat.codes
# home - 1
# away - 0

In [10]:
matches.reset_index(drop=True, inplace=True)

In [11]:
matches

,date,round,venue,result,gf,ga,opponent,xg,xga,poss,...,clr,err,touches,touches def pen,touches def 3rd,touches mid 3rd,touches att 3rd,touches att pen,season,team
0,2023-08-11,1,0,1,3,0,Burnley,1.9,0.3,65.0,...,7,2,835,75,267,412,158,23,2023-2024,Manchester City
1,2023-08-19,2,1,1,1,0,Newcastle Utd,1.0,0.3,59.0,...,10,1,788,65,212,411,174,21,2023-2024,Manchester City
2,2023-08-27,3,0,1,2,1,Sheffield Utd,3.5,0.7,79.0,...,6,0,893,40,153,440,304,53,2023-2024,Manchester City
3,2023-09-02,4,1,1,5,1,Fulham,2.2,1.4,68.0,...,11,0,838,64,222,483,138,20,2023-2024,Manchester City
4,2023-09-16,5,0,1,3,1,West Ham,3.6,0.9,68.0,...,9,0,837,49,148,382,311,49,2023-2024,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,2022-04-30,35,0,-1,0,2,Aston Villa,0.5,1.8,55.0,...,9,0,636,75,257,266,120,17,2021-2022,Norwich City
2276,2022-05-08,36,1,-1,0,4,West Ham,0.8,3.0,37.0,...,20,1,498,58,172,214,119,16,2021-2022,Norwich City
2277,2022-05-11,21,0,-1,0,3,Leicester City,1.1,2.0,35.0,...,37,0,527,96,257,184,94,18,2021-2022,Norwich City
2278,2022-05-15,37,0,0,1,1,Wolves,1.1,0.9,36.0,...,23,0,470,95,248,176,57,13,2021-2022,Norwich City
2279,2022-05-22,38,1,-1,0,5,Tottenham,0.5,3.4,41.0,...,7,1,513,60,184,233,98,16,2021-2022,Norwich City

In [12]:
# matches.loc[(matches['team'] == 'Luton Town') & (matches['season'] == '2023-2024'), 'team'] = 'Leicester City'
# matches.loc[(matches['team'] == 'Burnley')& (matches['season'] == '2023-2024'), 'team'] = 'Ipswich Town'
# matches.loc[(matches['team'] == 'Sheffield United') & (matches['season'] == '2023-2024'), 'team'] = 'Southampton'
# for out_team in ['Leeds United', 'Watford', 'Norwich City',  'Luton Town', 'Burnley', 'Sheffield United']:
#   matches = matches[matches["team"] != out_team]
# matches.reset_index(drop=True, inplace=True)

In [13]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton",
              "Manchester United": "Manchester Utd",
              "Newcastle United": "Newcastle Utd",
              "Tottenham Hotspur": "Tottenham",
              "West Ham United": "West Ham",
              "Wolverhampton Wanderers": "Wolves",
              "Nottingham Forest": "Nott'ham Forest",
              "Sheffield United": "Sheffield Utd"}
mapping = MissingDict(**map_values)

In [27]:
standings_url = 'https://fbref.com/en/comps/9/2023-2024/2023-2024-Premier-League-Stats'
soup = BeautifulSoup(data.text)
data = requests.get(standings_url)
rank_table = pd.read_html(data.text)[0]
rank_table

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Attendance,Top Team Scorer,Goalkeeper,Notes
0,1,Manchester City,38,28,7,3,96,34,62,91,2.39,80.5,35.6,44.9,1.18,53012,Erling Haaland - 27,Ederson,→ Champions League via league finish
1,2,Arsenal,38,28,5,5,91,29,62,89,2.34,76.1,27.9,48.2,1.27,60236,Bukayo Saka - 16,David Raya,→ Champions League via league finish
2,3,Liverpool,38,24,10,4,86,41,45,82,2.16,87.8,45.7,42.0,1.11,55979,Mohamed Salah - 18,Alisson,→ Champions League via league finish
3,4,Aston Villa,38,20,8,10,76,61,15,68,1.79,63.3,59.9,3.4,0.09,41858,Ollie Watkins - 19,Emiliano Martínez,→ Champions League via league finish
4,5,Tottenham,38,20,6,12,74,61,13,66,1.74,68.2,63.4,4.8,0.13,61482,Son Heung-min - 17,Guglielmo Vicario,→ Europa League via league finish
5,6,Chelsea,38,18,9,11,77,63,14,63,1.66,74.5,58.1,16.4,0.43,39524,Cole Palmer - 22,Đorđe Petrović,→ Europa League via league finish
6,7,Newcastle Utd,38,18,6,14,85,62,23,60,1.58,76.0,61.4,14.6,0.38,52125,Alexander Isak - 21,Martin Dúbravka,→ Europa Conference League via league finish
7,8,Manchester Utd,38,18,6,14,57,58,-1,60,1.58,56.5,68.9,-12.5,-0.33,73533,"Rasmus Højlund, Bruno Fernandes - 10",André Onana,NaN
8,9,West Ham,38,14,10,14,60,74,-14,52,1.37,52.3,71.1,-18.8,-0.49,62567,Jarrod Bowen - 16,Alphonse Areola,NaN
9,10,Crystal Palace,38,13,10,15,57,58,-1,49,1.29,48.6,52.0,-3.4,-0.09,24932,Jean-Philippe Mateta - 16,Sam Johnstone,NaN
10,11,Brighton,38,12,12,14,55,62,-7,48,1.26,56.8,55.4,1.4,0.04,32638,João Pedro - 9,Bart Verbruggen,NaN
11,12,Bournemouth,38,13,9,16,54,67,-13,48,1.26,55.9,58.1,-2.2,-0.06,11103,Dominic Solanke - 19,Neto,NaN
12,13,Fulham,38,13,8,17,55,61,-6,47,1.24,50.8,62.9,-12.1,-0.32,24302,Rodrigo Muniz - 9,Bernd Leno,NaN
13,14,Wolves,38,13,7,18,50,65,-15,46,1.21,46.7,67.7,-21.0,-0.55,31029,"Hwang Hee-chan, Matheus Cunha - 12",José Sá,NaN
14,15,Everton,38,13,9,16,40,51,-11,42,1.11,54.0,55.2,-1.2,-0.03,39042,"Abdoulaye Doucouré, Dominic Calvert-Lewin - 7",Jordan Pickford,6-point deduction 1
15,16,Brentford,38,10,9,19,56,65,-9,39,1.03,58.2,56.0,2.2,0.06,17082,Yoane Wissa - 12,Mark Flekken,NaN
16,17,Nott'ham Forest,38,9,9,20,49,67,-18,32,0.84,49.9,53.2,-3.3,-0.09,29386,Chris Wood - 14,Matt Turner,4-point deduction 2
17,18,Luton Town,38,6,8,24,52,85,-33,26,0.68,42.4,78.0,-35.5,-0.94,11240,Carlton Morris - 11,Thomas Kaminski,Relegated
18,19,Burnley,38,5,9,24,41,78,-37,24,0.63,40.6,70.4,-29.7,-0.78,21184,Jacob Bruun Larsen - 6,James Trafford,Relegated
19,20,Sheffield Utd,38,3,7,28,35,104,-69,16,0.42,38.3,76.7,-38.4,-1.01,30011,"Oliver McBurnie, Ben Brereton - 6",Wes Foderingham,Relegated

In [28]:
for season in ['2023-2024', '2022-2023', '2021-2022']:
  season_matches = matches[matches['season'] == season]
  standings_url = f'https://fbref.com/en/comps/9/{season}/{season}-Premier-League-Stats'
  data = requests.get(standings_url)
  soup = BeautifulSoup(data.text)
  data = requests.get(standings_url)

  rank_table = pd.read_html(data.text)[0]
  rank_table = rank_table[['Rk', 'Squad']]
  rank_dict = rank_table.set_index('Squad').to_dict()['Rk']

  season_matches['team'] = season_matches['team'].map(mapping)
  for team in season_matches['team'].unique():
    matches.loc[(matches['season'] == season) & (matches['team'] == team), 'team_rank'] = rank_dict[team]
    matches.loc[(matches['season'] == season) & (matches['opponent'] == team), 'opp. team_rank'] = rank_dict[team]

<ipython-input-28-3d6142b3b1f0>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_matches['team'] = season_matches['team'].map(mapping)
<ipython-input-28-3d6142b3b1f0>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_matches['team'] = season_matches['team'].map(mapping)
<ipython-input-28-3d6142b3b1f0>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  season_matches['team'] = season_matches['team'].map(mapping)

In [29]:
matches

,date,round,venue,result,gf,ga,opponent,xg,xga,poss,...,touches,touches def pen,touches def 3rd,touches mid 3rd,touches att 3rd,touches att pen,season,team,team_rank,opp. team_rank
0,2023-08-11,1,0,1,3,0,Burnley,1.9,0.3,65.0,...,835,75,267,412,158,23,2023-2024,Manchester City,1.0,19.0
1,2023-08-19,2,1,1,1,0,Newcastle Utd,1.0,0.3,59.0,...,788,65,212,411,174,21,2023-2024,Manchester City,1.0,7.0
2,2023-08-27,3,0,1,2,1,Sheffield Utd,3.5,0.7,79.0,...,893,40,153,440,304,53,2023-2024,Manchester City,1.0,20.0
3,2023-09-02,4,1,1,5,1,Fulham,2.2,1.4,68.0,...,838,64,222,483,138,20,2023-2024,Manchester City,1.0,13.0
4,2023-09-16,5,0,1,3,1,West Ham,3.6,0.9,68.0,...,837,49,148,382,311,49,2023-2024,Manchester City,1.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,2022-04-30,35,0,-1,0,2,Aston Villa,0.5,1.8,55.0,...,636,75,257,266,120,17,2021-2022,Norwich City,20.0,14.0
2276,2022-05-08,36,1,-1,0,4,West Ham,0.8,3.0,37.0,...,498,58,172,214,119,16,2021-2022,Norwich City,20.0,7.0
2277,2022-05-11,21,0,-1,0,3,Leicester City,1.1,2.0,35.0,...,527,96,257,184,94,18,2021-2022,Norwich City,20.0,8.0
2278,2022-05-15,37,0,0,1,1,Wolves,1.1,0.9,36.0,...,470,95,248,176,57,13,2021-2022,Norwich City,20.0,10.0
2279,2022-05-22,38,1,-1,0,5,Tottenham,0.5,3.4,41.0,...,513,60,184,233,98,16,2021-2022,Norwich City,20.0,4.0

In [ ]:
matches[matches["team_rank"] == None]

Empty DataFrame
Columns: [date, round, venue, result, gf, ga, opponent, xg, xga, poss, sh_x, sot, sot%, g/sh, g/sot, npxg, npxg/sh, g-xg, np:g-xg, completed passes, passes attempted, completed passes %, totdist, prgdist, ast, xag, xa, kp, tkl, tklw, takles def 3rd, takles mid 3rd, takles att 3rd, blocks, shots blocked, passes blocked, int, tkl+int, clr, err, touches, touches def pen, touches def 3rd, touches mid 3rd, touches att 3rd, touches att pen, season, team, team_rank, opp. team_rank]
Index: []

[0 rows x 50 columns]

In [ ]:
# new_season_rank_dict = {'Manchester City': 1,
#  'Arsenal': 2,
#  'Liverpool': 3,
#  'Aston Villa': 4,
#  'Tottenham': 5,
#  'Chelsea': 6,
#  'Newcastle Utd': 7,
#  'Manchester Utd': 8,
#  'West Ham': 9,
#  'Crystal Palace': 10,
#  'Brighton': 11,
#  'Bournemouth': 12,
#  'Fulham': 13,
#  'Wolves': 14,
#  'Everton': 15,
#  'Brentford': 16,
#  "Nott'ham Forest": 17,
#  'Leicester City': 18,
#  'Ipswich Town': 19,
#  'Southampton': 20}

In [34]:
plt.figure(figsize=(10,6))
team_stats = matches.groupby(by=matches['team']).sum()
print(team_stats)

TypeError: datetime64 type does not support sum operations